title: Trilochan Parvathaneni
logo: /assets/img/logo.png
description: 
  Currently I am working as Senior Analyst Data Operations. Good at SQL, Big Query. Team Management. 
  Had experience in HR, Finance, Recruitment, Resource Management. 
  Had experience in Zoho tools.
theme: jekyll-theme-minimal
